Queen attack: new practice exercise
exercism/r pull request #244
Opened 2023-04-17 00:27 UTC by colinleach

Some questions:
- Is `list` a good way to implement the queen's position? There are various other options.
- Is it a good idea to check for specific error messages? I see that older exercises only check for a generic error, but I don't know why.

I'm creating this PR now, but you may want to delay review until I've had feedback on earlier PRs. I assume I still have plenty to learn about this process, to make life easier for the reviewers.

2023-04-25 22:33 UTC, jonmcalder requested changes
Nothing wrong with using a list to implement the Queen's position, but I think I'd prefer to test only the outcomes i.e. simply expect_error() for create() with invalid positions, and true/false for can_attack(). If learners aren't restricted to a specific implementation then learning and mentoring opportunities are more open ended which I see as a good thing as long as the instructions and expectations (tests) are clear which I think they are.

2023-04-25 22:46 UTC, colinleach commented
I already tested this change locally, so it's an easy PR to send. Give me a few minutes - I'm currently in the middle of a minor domestic situation.

2023-04-25 22:58 UTC, jonmcalder commented
Oh, and re checking for specific error messages vs a generic error, I'm open to be persuaded othewise, but have generally felt that a lighter touch for error checking is better for most exercises since the different possible error states either aren't meaningfully different, or could presumably easily have been differentiated if they have each been detected / checked reliably.

Or in other words, requiring a certain error message or custom error class expectation seems like it would add unnecessary friction (especially for earlier exercises when other fundamental learning objectives should be the focus). But again, I'm open to suggestions on how error testing could / should be done better if it's not consistent or rigorous enough. Maybe for practice exercises beyond a certain point, or with higher difficulty, error expectations should be more strict?

2023-04-25 23:00 UTC, jonmcalder commented on exercises/practice/queen-attack/queen-attack.R
> +  }
```suggestion
}
```

2023-04-25 23:02 UTC, jonmcalder commented on config.json
> +        "status": "wip",
```suggestion
        "status": "active",
```

2023-04-25 23:52 UTC, colinleach commented
I think I got all the changes in, including removal of specific error messages: those were taken from `canonical-data.json` but I don't have strong views either way about including them.

2023-04-26 08:07 UTC, jonmcalder commented on exercises/practice/queen-attack/test_queen-attack.R
> +  expect_error(create(row, col), NA)
```suggestion
  expect_error(create(row, col))
```

2023-04-26 08:23 UTC, jonmcalder commented on exercises/practice/queen-attack/test_queen-attack.R
> +  expect_error(create(row, col), NA)
```suggestion
  expect_no_error(create(row, col))
```

This is a relatively recently addition to {testthat}, but is preferred since it makes the intent clearer.

2023-04-26 08:26 UTC, jonmcalder approved these changes
Thank you!

2023-04-26 08:32 UTC, merged